// One-time starter data for the Reach Out tracker, imported from a spreadsheet.
// Deduped to a single entry per person (their most recent row). `cadenceDays`
// null means "no cadence" (archived contacts with no active reach-out rhythm).
// Dates are YYYY-MM-DD. `done` mirrors the sheet's TRUE/FALSE = reached out this
// cycle. Holiday rows (e.g. Father's Day) were intentionally left out.
export const REACH_OUT_SEED = [
  { name: 'Johnny Delsandro', category: 'Family', method: 'Text', cadenceDays: 5, lastReachOut: '2026-06-19', note: '', birthday: '2026-03-27', done: false },
  { name: 'Kyle Smith', category: 'City Friends', method: 'Text', cadenceDays: 6, lastReachOut: '2026-06-16', note: '', birthday: '2026-04-26', done: false },
  { name: 'Duncan Pratt-Stephen', category: 'City Friends', method: 'Text', cadenceDays: 6, lastReachOut: '2026-06-17', note: '', birthday: '2026-04-24', done: false },
  { name: 'Katie Baldauf', category: 'Family', method: 'Text', cadenceDays: 5, lastReachOut: '2026-06-12', note: '', birthday: '2026-12-10', done: true },
  { name: 'Mike Susa', category: 'City Friends', method: 'Text', cadenceDays: 7, lastReachOut: '2026-06-20', note: '', birthday: '2026-05-18', done: false },
  { name: 'Mom', category: 'Family', method: 'Text', cadenceDays: 5, lastReachOut: '2026-06-17', note: 'New house', birthday: '2026-08-20', done: true },
  { name: 'Laura Sova', category: 'Family', method: 'Text', cadenceDays: 5, lastReachOut: '2026-06-15', note: 'Otis', birthday: '2026-08-24', done: true },
  { name: 'Amanda Brehove', category: 'Family', method: 'Text', cadenceDays: 5, lastReachOut: '2026-06-20', note: 'Schedule something w/Joanne', birthday: '2026-06-30', done: false },
  { name: 'Dad', category: 'Family', method: 'Text', cadenceDays: 5, lastReachOut: '2026-06-14', note: '', birthday: '2026-11-14', done: false },
  { name: 'Mike Baldauf', category: 'Family', method: 'Text', cadenceDays: 5, lastReachOut: '2026-06-16', note: '', birthday: '2026-05-20', done: false },
  { name: 'Ryan Mullins', category: 'Far Away Friends', method: 'Text', cadenceDays: 65, lastReachOut: '2026-04-17', note: '', birthday: '2026-04-17', done: false },
  { name: 'Joanne (Joo Yeon) Seo', category: 'GF', method: 'Text', cadenceDays: 1, lastReachOut: '2026-06-21', note: '', birthday: '2026-04-03', done: false },
  { name: 'Kate Boucher', category: 'Npt Friends', method: 'Text', cadenceDays: 30, lastReachOut: '2026-05-28', note: '', birthday: '', done: false },
  { name: 'Guy Brooks', category: 'City Friends', method: 'Text', cadenceDays: 45, lastReachOut: '2026-05-14', note: '', birthday: '2026-10-20', done: true },
  { name: 'Milan Sova', category: 'City Friends', method: 'Text', cadenceDays: 50, lastReachOut: '2026-05-09', note: '', birthday: '2026-08-23', done: false },
  { name: 'Greg Buron', category: 'City Friends', method: 'Text', cadenceDays: 60, lastReachOut: '2026-05-07', note: '', birthday: '2026-03-14', done: true },
  { name: 'Adam Herzog', category: 'Npt Friends', method: 'Text', cadenceDays: 30, lastReachOut: '2026-06-09', note: '', birthday: '2026-03-27', done: true },
  { name: 'Sunnie Baldauf', category: 'Family', method: 'Text', cadenceDays: 50, lastReachOut: '2026-05-22', note: '', birthday: '2026-03-31', done: false },
  { name: 'Will Pratt-Stephen', category: 'City Friends', method: 'Text', cadenceDays: 30, lastReachOut: '2026-06-14', note: '', birthday: '2026-06-19', done: true },
  { name: 'Ashley Soarez', category: 'City Friends', method: 'Text', cadenceDays: 30, lastReachOut: '2026-06-19', note: '', birthday: '2026-09-05', done: false },
  { name: 'Aunt Celia', category: 'Family', method: 'Text', cadenceDays: 75, lastReachOut: '2026-05-05', note: '', birthday: '2026-05-25', done: false },
  { name: 'Juan Perez', category: 'City Friends', method: 'Text', cadenceDays: 50, lastReachOut: '2026-05-31', note: '', birthday: '2026-02-19', done: true },
  { name: 'Ben Haffner', category: 'City Friends', method: 'Text', cadenceDays: 45, lastReachOut: '2026-06-14', note: 'Vivienne, Xander', birthday: '2026-09-05', done: true },
  { name: 'Jordan Brehove', category: 'Family', method: 'Text', cadenceDays: 125, lastReachOut: '2026-05-30', note: '', birthday: '2026-08-16', done: false },
  { name: 'Lisa Mcgrath', category: 'City Friends', method: 'Text', cadenceDays: 50, lastReachOut: '2026-04-14', note: '', birthday: '', done: false },
  { name: 'Amanda Scharali', category: 'Npt Friends', method: 'Text', cadenceDays: null, lastReachOut: '2025-11-09', note: '', birthday: '', done: true },
  { name: 'Colm', category: 'Npt Friends', method: 'Text', cadenceDays: null, lastReachOut: '2024-08-18', note: '', birthday: '', done: true },
  { name: 'Jeb', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2024-04-02', note: '', birthday: '', done: false },
  { name: 'Kyra', category: 'Girlfriend', method: 'Call', cadenceDays: null, lastReachOut: '2024-03-12', note: '', birthday: '', done: false },
  { name: 'Jack Finken', category: 'Family', method: 'Text', cadenceDays: null, lastReachOut: '2023-11-14', note: '', birthday: '', done: false },
  { name: 'Ben Dinter', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2024-02-18', note: '', birthday: '', done: false },
  { name: 'William Papillon', category: 'Far Away Friends', method: '', cadenceDays: null, lastReachOut: '', note: '', birthday: '', done: false },
  { name: 'Aston', category: 'City Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-07-19', note: '', birthday: '', done: false },
  { name: 'Adam E', category: 'City Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-07-19', note: '', birthday: '', done: false },
  { name: 'Adriana', category: 'City Friends', method: 'Text', cadenceDays: null, lastReachOut: '2021-10-27', note: '', birthday: '', done: false },
  { name: 'Amanda Schram', category: 'City Friends', method: 'Text', cadenceDays: null, lastReachOut: '2023-01-07', note: '', birthday: '', done: false },
  { name: 'Ben Bieler', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-01-16', note: '', birthday: '', done: false },
  { name: 'Ben H', category: 'City Friends', method: 'Call', cadenceDays: null, lastReachOut: '2023-05-26', note: '', birthday: '', done: false },
  { name: 'Bobby McLawhorn', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-05-22', note: '', birthday: '', done: false },
  { name: 'Brendan Ratner', category: 'Npt Friends', method: 'Call', cadenceDays: null, lastReachOut: '2023-05-26', note: '', birthday: '', done: false },
  { name: 'Clay', category: 'City Friends', method: 'Text', cadenceDays: null, lastReachOut: '2023-01-14', note: '', birthday: '', done: false },
  { name: 'Eric Hebel', category: 'Npt Friends', method: 'Text', cadenceDays: null, lastReachOut: '2023-07-08', note: '', birthday: '', done: false },
  { name: 'Jess', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-09-18', note: '', birthday: '', done: false },
  { name: 'Joel', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-06-07', note: '', birthday: '', done: false },
  { name: 'Lee Johnson', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-04-02', note: '', birthday: '', done: false },
  { name: 'Manheimer', category: 'City Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-02-17', note: '', birthday: '', done: false },
  { name: 'Matt Borek', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-10-22', note: '', birthday: '', done: false },
  { name: 'Matt Slatt', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2021-04-26', note: '', birthday: '', done: false },
  { name: 'Jordan Miller', category: 'Far Away Friends', method: 'Call', cadenceDays: null, lastReachOut: '2023-05-26', note: '', birthday: '', done: false },
  { name: 'Phillpi', category: 'Far Away Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-01-16', note: '', birthday: '', done: false },
  { name: 'Skyler', category: 'City Friends', method: 'Text', cadenceDays: null, lastReachOut: '2022-04-15', note: '', birthday: '', done: false },
];
